# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JyGTc3HBFHKdL2Rtkai7-euwKE3Mca91
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sb

contract_values = pd.read_csv('/content/drive/My Drive/Data Analysis Teams/Contract Pricing/Datasets/MAIN Dataset/contract_values.csv')

contract_values.columns = contract_values.iloc[0]

contract_values = contract_values[1:]

contract_values = contract_values.drop(columns = ['Signed Using'])

contract_values.head()

player_season_stats = pd.read_csv('/content/drive/My Drive/Data Analysis Teams/Contract Pricing/Datasets/MAIN Dataset/Season_Stats.csv')

player_season_stats = player_season_stats[player_season_stats['Year'] >= 1990]
for i, player in player_season_stats.iterrows():
  player_season_stats.loc[i, 'Player'] = player_season_stats.loc[i, 'Player'].replace(r'*', '')
player_season_stats = player_season_stats.drop(columns = ['Unnamed: 0', '3PAr', 'FTr', 'WS/48', 'WS', 'GS', 'BPM', 'FG', '2P', 'FT', 'TRB'])

player_season_stats.head()

salaries_1985to2018 = pd.read_csv('/content/drive/My Drive/Data Analysis Teams/Contract Pricing/Datasets/MAIN Dataset/salaries_1985to2018.csv')

salaries_1985to2018 = salaries_1985to2018[salaries_1985to2018['season_start'] >= 1990]
salaries_1985to2018 = salaries_1985to2018.drop(columns = 'league')

salaries_1985to2018.head()

players = pd.read_csv('/content/drive/My Drive/Data Analysis Teams/Contract Pricing/Datasets/MAIN Dataset/players.csv')

players = players[['_id', 'name']]

players.head()

players_salaries = pd.merge(salaries_1985to2018, players, how = 'left', left_on = 'player_id', right_on = '_id')
players_salaries = players_salaries.drop(columns = ['_id', 'player_id', 'season_end', 'season'])
player_season_stats["Year"] = player_season_stats["Year"].astype(int)
players_salaries = pd.merge(players_salaries, player_season_stats, how = 'left', left_on = ['name', 'season_start'], right_on = ['Player', 'Year'])
players_salaries = players_salaries.drop(columns = 'name')
players_salaries = players_salaries.dropna()
players_salaries.head()

salary_cap = pd.read_csv('/content/drive/My Drive/Data Analysis Teams/Contract Pricing/Datasets/MAIN Dataset/salary_cap_history.csv')

for i, year in salary_cap.iterrows():
  salary_cap.loc[i, 'Year'] = salary_cap.loc[i, 'Year'][0:4]



  
salary_cap.rename(columns={'Year': 'season_start'}, inplace=True)
salary_cap.loc[33, 'Real Salary Cap'] = "$93,532,801";
salary_cap.loc[34] = ['2018', '$101,869,000', '$94,036,372']
salary_cap

salary_percentages = [float(players_salaries.loc[i, 'salary'] / float((salary_cap.at[player['season_start']-1984, 'Nominal Cap']).replace(',', '')[1:])) for i, player in players_salaries.iterrows()]
players_salaries['Cap %'] = salary_percentages

players_salaries.sort_values(by=['salary'], inplace=True)
max_val = max(players_salaries['salary'])
print(max_val)
players_salaries.drop(columns = 'team', inplace=True)

ppg = []
for pts, games in zip(players_salaries['PTS'], players_salaries['G']):
  ppg.append(float(pts) / float(games))
players_salaries['PPG'] = ppg

orbpg = []
for orb, games in zip(players_salaries['ORB'], players_salaries['G']):
  orbpg.append(float(orb) / float(games))
players_salaries['ORBPG'] = orbpg

drbpg = []
for drb, games in zip(players_salaries['DRB'], players_salaries['G']):
  drbpg.append(float(drb) / float(games))
players_salaries['DRBPG'] = drbpg

apg = []
for ast, games in zip(players_salaries['AST'], players_salaries['G']):
  apg.append(float(ast) / float(games))
players_salaries['APG'] = apg

spg = []
for stl, games in zip(players_salaries['STL'], players_salaries['G']):
  spg.append(float(stl) / float(games))
players_salaries['SPG'] = spg

bpg = []
for blk, games in zip(players_salaries['BLK'], players_salaries['G']):
  bpg.append(float(blk) / float(games))
players_salaries['BPG'] = bpg

tpg = []
for tov, games in zip(players_salaries['TOV'], players_salaries['G']):
  tpg.append(float(tov) / float(games))
players_salaries['TPG'] = tpg

pfpg = []
for pf, games in zip(players_salaries['PF'], players_salaries['G']):
  pfpg.append(float(pf) / float(games))
players_salaries['PFPG'] = pfpg

positions = []
pos_dict = {'PG' : 0, 'SG' : 1, 'SF' : 2, 'PF' : 3, 'C' : 4}
for pos in players_salaries['Pos']:
  positions.append(pos_dict[pos[0:2] if pos[0] != 'C' else pos[0]])
players_salaries['Pos'] = positions

players_salaries.drop(inplace=True, columns=['ORB', 'DRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year'])

players_salaries

from google.colab import files
# model_save_name = 'player_data.csv'
# path = F"/content/drive/My Drive/Data Analysis Teams/Contract Pricing/Datasets/MAIN Dataset/{model_save_name}" 
# players_salaries.to_csv(path)
# files.download(path)

# model_save_name = 'player_numeric_data.csv'
# path = F"/content/drive/My Drive/Data Analysis Teams/Contract Pricing/Datasets/MAIN Dataset/{model_save_name}" 
# cols_to_drop = ['Player', 'Tm', 'salary'] #quantify these stats later
# players_numeric = players_salaries.drop(cols_to_drop, axis=1)
# players_numeric.to_csv(path)
# files.download(path)

model_save_name = 'nba_players_dependent.csv'
path = F"/content/drive/My Drive/Data Analysis Teams/Contract Pricing/Datasets/MAIN Dataset/{model_save_name}" 
cols_to_drop = ['salary']
nba_players_dependent = players_salaries.drop(cols_to_drop, axis=1)
nba_players_dependent.to_csv(path)
files.download(path)

